const nav=document.querySelector('.nav'),menuToggle=document.querySelector('.menu-toggle'),mobileMenu=document.querySelector('.mobile-menu');
window.addEventListener('scroll',()=>nav.classList.toggle('scrolled',scrollY>20),{passive:true});
menuToggle?.addEventListener('click',()=>{const open=mobileMenu.classList.toggle('open');menuToggle.setAttribute('aria-expanded',open);mobileMenu.setAttribute('aria-hidden',!open)});
document.querySelectorAll('.mobile-menu a').forEach(a=>a.addEventListener('click',()=>{mobileMenu.classList.remove('open');menuToggle.setAttribute('aria-expanded','false');mobileMenu.setAttribute('aria-hidden','true')}));
const reduce=matchMedia('(prefers-reduced-motion:reduce)').matches;
const io=new IntersectionObserver(es=>es.forEach(e=>{if(e.isIntersecting){e.target.classList.add('in-view');io.unobserve(e.target)}}),{threshold:.12});
document.querySelectorAll('.reveal').forEach(e=>io.observe(e));
function typeText(el,text,speed=14){return new Promise(done=>{if(reduce){el.textContent=text;el.classList.add('done');done();return}let i=0;const tick=()=>{el.textContent=text.slice(0,i++);if(i<=text.length)setTimeout(tick,speed+Math.random()*20);else{el.classList.add('done');done()}};tick()})}
const tio=new IntersectionObserver(es=>{es.forEach(async e=>{if(!e.isIntersecting)return;const el=e.target;tio.unobserve(el);await typeText(el,el.dataset.typing||'',el.classList.contains('typing-terminal')?15:12)})},{threshold:.35});
document.querySelectorAll('[data-typing]').forEach(e=>tio.observe(e));
const heroTyping=document.getElementById('heroTyping');if(heroTyping){const p=['designing systems that scale','turning requirements into architecture','shipping secure product experiences','engineering for measurable outcomes'];let n=0,i=0,del=false;const loop=()=>{if(reduce){heroTyping.textContent=p[0];return}const s=p[n];heroTyping.textContent=s.slice(0,i);if(!del){i++;if(i>s.length){del=true;setTimeout(loop,1200);return}}else{i--;if(i===0){del=false;n=(n+1)%p.length}}setTimeout(loop,del?32:52)};loop()}
if(matchMedia('(pointer:fine)').matches&&!reduce){const glow=document.createElement('div');glow.className='cursor-glow';document.body.appendChild(glow);addEventListener('pointermove',e=>{glow.style.left=e.clientX+'px';glow.style.top=e.clientY+'px'},{passive:true});document.querySelectorAll('[data-tilt]').forEach(card=>{card.addEventListener('pointermove',e=>{const r=card.getBoundingClientRect(),x=(e.clientX-r.left)/r.width-.5,y=(e.clientY-r.top)/r.height-.5;card.style.transform=`perspective(1200px) rotateX(${y*-2.5}deg) rotateY(${x*3.5}deg) translateY(-4px)`});card.addEventListener('pointerleave',()=>card.style.transform='')})}
document.getElementById('year').textContent=new Date().getFullYear();
document.getElementById('contactForm')?.addEventListener('submit',e=>{e.preventDefault();const d=new FormData(e.currentTarget);location.href=`mailto:itsaymendevops@gmail.com?subject=${encodeURIComponent('Portfolio enquiry from '+d.get('name'))}&body=${encodeURIComponent('Name: '+d.get('name')+'\nEmail: '+d.get('email')+'\n\n'+d.get('message'))}`});
